### ISSUE TITLE
Subroutines redefined 

### ISSUE THREAD

**Issue by eaoliver** [maxmind/MaxMind-DB-Reader-perl#30] opened 2016-05-20 06:15 UTC
This library has some annoying issues that I haven't been able to disable.  At runtime when loading the database I get a large dump to STDERR as follows: 

Subroutine GeoIP2::Database::Reader::new redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Database::Reader::metadata redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Database::Reader::_assert__reader redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Database::Reader::file redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Reader::PP::new redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Reader::Role::Reader::file redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Reader::Role::HasMetadata::metadata redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Reader::Role::Sysreader::_data_source_size redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Reader::Role::Sysreader::data_source redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Reader::Role::HasMetadata::_set_data_section_end redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Reader::Decoder::new redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Metadata::new redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Metadata::database_type redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Database::Reader::_reader redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Reader::Role::HasMetadata::ip_version redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Reader::Role::HasMetadata::_assert_metadata redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Metadata::ip_version redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Reader::PP::_ipv4_start_node redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Reader::Role::NodeReader::_node_byte_size redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Reader::Role::HasMetadata::record_size redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Metadata::record_size redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Reader::Role::HasMetadata::node_count redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Metadata::node_count redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Reader::Role::NodeReader::_search_tree_size redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Reader::Role::HasDecoder::_decoder redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine MaxMind::DB::Reader::Decoder::_pointer_base redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Role::HasLocales::locales redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Model::City::new redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Model::City::country redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Model::City::_raw_country redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Record::Country::new redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Role::Model::HasSubdivisions::_subdivisions redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Role::Model::HasSubdivisions::_raw_subdivisions redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Record::Subdivision::new redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Model::City::city redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Model::City::_raw_city redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Record::City::new redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Role::Record::Country::iso_code redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Role::Record::HasNames::name redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Role::Record::HasNames::names redefined at /usr/share/perl5/Sub/Defer.pm line 30.
Subroutine GeoIP2::Role::Record::Country::geoname_id redefined at /usr/share/perl5/Sub/Defer.pm line 30.

I'm running the latest distribution of all dependencies of GeoIP2::Database::Reader as of this posting.

**Comment by oschwald** [comment] 2016-05-20 14:06
Could you try running your code with [circular::require](https://metacpan.org/pod/circular::require)? These  sorts of warnings are usually a symptom of import cycles.

**Comment by eaoliver** [comment] 2016-05-20 17:28
The only new output is:

Circular require detected:
  MaxMind/DB/Reader.pm
  MaxMind/DB/Reader.pm

**Comment by oschwald** [comment] 2016-05-20 17:45
Could you provide a small test case that reproduces the issue?

**Comment by oschwald** [comment] 2016-05-27 15:17
I am going to close this as we can't reproduce it. I am happy to re-open it given a test case or more specific instructions on how to reproduce it.

**Closed by oschwald** 2016-05-27 15:17 UTC
